<?php

namespace Acme\SaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategogyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategogyRepository extends EntityRepository
{

	 public function retrieve_all(){
        $query = $this->getEntityManager()->createQuery('SELECT mg FROM AcmeSaleBundle:Categogy AS mg ORDER BY mg.id ASC');
        return $query->getResult();
    }
}
