<?php

namespace Acme\SaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Product_descriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_descriptionRepository extends EntityRepository
{
}
